import {StyleSheet} from 'react-native';

export const DetailScreenStyle = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
  },
  header: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3C50AF',
    paddingVertical: 20,
  },
  title: {
    flexGrow: 1,
    textAlign: 'center',
    color: 'white',
    fontSize: 22,
    fontFamily: 'Quicksand-Bold',
    marginHorizontal: 40,
  },
  iconCloseWrapper: {
    position: 'absolute',
    top: 20,
    right: 10,
    width: 30,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconClose: {
    color: 'white',
    fontSize: 24,
  },
  contentContainer: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    flex: 1,
    backgroundColor: 'white',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  error: {
    fontSize: 22,
    fontFamily: 'Quicksand-Bold',
    color: '#3C50AF',
    marginBottom: 30,
    width: '100%',
    textAlign: 'center',
  },
  tryButton: {
    backgroundColor: '#3C50AF',
    paddingHorizontal: 25,
    paddingVertical: 8,
    borderRadius: 5,
  },
  tryText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Quicksand-Bold',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  loading: {
    fontSize: 20,
    fontFamily: 'Quicksand-Bold',
    width: '100%',
    textAlign: 'center',
    paddingVertical: 20,
    color: '#3C50AF',
  },
});

export const CreateFunctionStyle = StyleSheet.create({
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyImgContainer: {
    width: 65,
    height: 50,
  },
  emptyImg: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  emptyText: {
    fontFamily: 'Quicksand-Bold',
    fontSize: 20,
    width: '100%',
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingTop: 30,
    opacity: 0.6,
  },
  emptyItemContainer: {
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 5,
  },
  emptyItemText: {
    width: '100%',
    textAlign: 'center',
    fontFamily: 'Quicksand-SemiBold',
    fontSize: 18,
    opacity: 0.6,
  },
  tkb_wrapper: {
    marginVertical: 20,
    paddingHorizontal: 5,
  },
  ten_hoc_ky: {
    fontFamily: 'Quicksand-Bold',
    fontSize: 16,
  },
  tkb_ngay_cn: {
    fontSize: 12,
    color: 'gray',
    fontFamily: 'Quicksand-Medium',
    paddingBottom: 10,
  },
  tkb_table_style: {
    borderWidth: 1,
    borderColor: 'white',
  },
  tkb_head_style: {
    backgroundColor: '#3C50AF',
  },
  tkb_head_text: {
    color: 'white',
    fontFamily: 'Quicksand-Bold',
    padding: 10,
    textAlign: 'center',
  },
  tkb_body_text: {
    fontFamily: 'Quicksand-Medium',
    padding: 10,
    textAlign: 'center',
    opacity: 0.6,
  },
  tkb_even_row: {
    backgroundColor: 'rgba(60, 80, 175, 0.1)',
  },
  lt_table_head: {
    flexDirection: 'row',
  },
  padding: {
    paddingTop: 10,
    marginTop: 10,
  },
  ngay_cn_bd: {
    fontSize: 12,
    color: '#3C50AF',
    fontFamily: 'Quicksand-Medium',
    width: '100%',
    textAlign: 'center',
  },
  summary_bd: {
    marginTop: 10,
    paddingTop: 10,
    borderTopColor: 'rgba(0, 0, 0, 0.1)',
    borderTopWidth: 1,
    paddingHorizontal: 8,
  },
  text_summary_bd: {
    fontFamily: 'Quicksand-Medium',
    paddingVertical: 4,
    opacity: 0.6,
    fontSize: 13,
  },
  bd_info_text: {
    width: '100%',
    textAlign: 'center',
    fontFamily: 'Quicksand-Bold',
    paddingBottom: 7,
    fontSize: 13,
    color: '#3C50AF',
  },
  bdTitle: {
    fontFamily: 'Quicksand-Bold',
    width: '100%',
    textAlign: 'center',
    fontSize: 20,
    paddingVertical: 20,
    color: '#3C50AF',
  },
  bdHeaderText: {
    fontFamily: 'Quicksand-SemiBold',
    color: '#3C50AF',
    paddingLeft: 10,
    paddingVertical: 5,
    opacity: 0.7,
  },
  bdHeaderValue: {
    color: 'red',
  },
  dcContainer: {
    paddingVertical: 30,
  },
  dcStudentName: {
    fontFamily: 'Quicksand-Regular',
    width: '100%',
    textAlign: 'center',
  },
  dcTitle: {
    width: '100%',
    textAlign: 'center',
    fontSize: 20,
    paddingBottom: 10,
    paddingTop: 20,
    opacity: 0.8,
    fontFamily: 'Quicksand-Bold',
  },
  hpText: {
    fontFamily: 'Quicksand-SemiBold',
    color: '#3C50AF',
    paddingVertical: 8,
    opacity: 0.8,
    fontSize: 14,
  },
  hpWrap: {
    paddingHorizontal: 8,
    paddingVertical: 10,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
    borderBottomWidth: 1,
  },
  numberHp: {
    color: 'red',
  },
  ttsvHeader: {
    width: '100%',
    paddingVertical: 30,
    paddingHorizontal: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ttsvHeaderText: {
    fontFamily: 'Quicksand-Bold',
    fontSize: 16,
    color: '#3C50AF',
  },
  ttsvHeaderStatus: {
    color: 'red',
  },
  ttsvText: {
    fontFamily: 'Quicksand-Regular',
    paddingHorizontal: 5,
    paddingVertical: 8,
  },
  ttsvItemHeader: {
    backgroundColor: 'gray',
    color: 'white',
    fontFamily: 'Quicksand-Bold',
  },
  ttsvEmpty: {
    width: '100%',
    textAlign: 'center',
    fontFamily: 'Quicksand-Bold',
    paddingHorizontal: 5,
    paddingVertical: 20,
    opacity: 0.6,
  },
  ttsvValue: {
    fontFamily: 'Quicksand-SemiBold',
  },
  titleLL: {
    width: '100%',
    backgroundColor: '#3C50AF',
  },
  titleLLText: {
    fontFamily: 'Quicksand-Bold',
    textTransform: 'uppercase',
    color: 'white',
    textAlign: 'center',
    width: '100%',
    fontSize: 16,
    paddingVertical: 8,
  },
  subTitleLL: {
    paddingVertical: 8,
    paddingHorizontal: 5,
    borderBottomWidth: 0.2,
    borderTopWidth: 0.2,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  subTitleTextLL: {
    fontFamily: 'Quicksand-SemiBold',
    width: '100%',
    textAlign: 'center',
    color: '#3C50AF',
  },
  subValueTextLL: {
    width: '100%',
    fontFamily: 'Quicksand-Regular',
  },
  normalLLContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
    paddingVertical: 8,
    borderBottomWidth: 0.2,
    borderTopWidth: 0.2,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  normalThLL: {
    width: '35%',
  },
  normalTdLL: {
    width: '65%',
  },
  normalThTextLL: {
    width: '100%',
    fontFamily: 'Quicksand-SemiBold',
  },
  normalTdTextLL: {
    width: '100%',
    fontFamily: 'Quicksand-Regular',
    paddingLeft: 10,
  },
});
